import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { projects, developers, enquiryDevelopers, captions, films } from '../src/content.js';
import { site, faqs, filmDescriptions } from '../src/site.js';
import { escapeHtml as e, renderProjectCard, projectPath, renderFilters } from '../src/render.js';

const url = path => new URL(path, site.origin).href;
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
const asset = (prefix, id, extension) => `/media/${prefix}-${String(id).padStart(2,'0')}.${extension}`;
const filmPath = id => `/films/film-${String(id).padStart(2,'0')}/`;
const referenceNote = 'Information is taken from supplied developer guides and official project sources, linked on each project page. Prices are indicative, availability is unconfirmed, and completion dates may vary by phase. Confirm the latest cost sheet, specifications, approvals and RERA details with the developer.';
const organization = {
  '@type':site.address ? 'RealEstateAgent' : 'Organization', '@id':url('/#organization'),
  name:site.name, url:url('/'), logo:{'@type':'ImageObject',url:url('/media/logo.svg')},
  description:'Property information and enquiry assistance for apartments, villaments and residential plots from multiple developers in Bengaluru.',
  areaServed:{'@type':'City',name:'Bengaluru'},
  ...(site.telephone ? {telephone:site.telephone} : {}), ...(site.email ? {email:site.email} : {}),
  ...(site.address ? {address:{'@type':'PostalAddress',...site.address}} : {}),
  ...(site.sameAs.length ? {sameAs:site.sameAs} : {}),
  ...(site.reraRegistration ? {identifier:{'@type':'PropertyValue',name:'RERA registration',value:site.reraRegistration}} : {}),
};
const website = {'@type':'WebSite','@id':url('/#website'),url:url('/'),name:site.name,inLanguage:'en-IN',publisher:{'@id':organization['@id']}};
const service = {'@type':'Service','@id':url('/#property-enquiry'),name:'Bengaluru property enquiry assistance',serviceType:'Residential property information and enquiry assistance',provider:{'@id':organization['@id']},areaServed:{'@type':'City',name:'Bengaluru'},url:url('/#enquire')};
const homeTitle = 'Bengaluru Homes from Trusted Developers | Trusted Properties';
const pages = [];
function breadcrumb(path, items) { return {'@type':'BreadcrumbList','@id':url(path+'#breadcrumbs'),itemListElement:items.map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:url(path)}))}; }
function webpage(path,title,description,type='WebPage',more={}) {return {'@type':type,'@id':url(path+'#webpage'),url:url(path),name:title,description,inLanguage:'en-IN',isPartOf:{'@id':website['@id']},publisher:{'@id':organization['@id']},...more};}
function itemList(items,path) {return {'@type':'ItemList','@id':url(path+'#collection'),name:'Multi-developer properties in Bengaluru',numberOfItems:items.length,itemListElement:items.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:url(projectPath(p))}))};}
function head({path,title,description,graph=[],image='/media/film-06.jpg',noindex=false,markdown=false}) {
 return `<title>${e(title)}</title>
<meta name="description" content="${e(description)}"/>
<link rel="canonical" href="${url(path)}"/>
<meta name="robots" content="${noindex?'noindex, follow':'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'}"/>
<meta property="og:type" content="website"/>
<meta property="og:site_name" content="${e(site.name)}"/>
<meta property="og:locale" content="en_IN"/>
<meta property="og:title" content="${e(title)}"/>
<meta property="og:description" content="${e(description)}"/>
<meta property="og:url" content="${url(path)}"/>
<meta property="og:image" content="${url(image)}"/>
<meta property="og:image:alt" content="Illustrative architecture from the Trusted Properties reference collection"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="${e(title)}"/>
<meta name="twitter:description" content="${e(description)}"/>
<meta name="twitter:image" content="${url(image)}"/>
<meta name="twitter:image:alt" content="Illustrative architecture from the Trusted Properties reference collection"/>
<link rel="sitemap" type="application/xml" href="/sitemap.xml"/>
<link rel="alternate" type="text/plain" title="LLM-readable site guide" href="/llms.txt"/>
${markdown?`<link rel="alternate" type="text/markdown" title="Markdown version" href="${path}index.md"/>`:''}
${site.googleVerification?`<meta name="google-site-verification" content="${e(site.googleVerification)}"/>`:''}
${site.bingVerification?`<meta name="msvalidate.01" content="${e(site.bingVerification)}"/>`:''}
<script type="application/ld+json">${json({'@context':'https://schema.org','@graph':[organization,website,...graph]})}</script>`;
}
const discovery = `<nav class="discovery-nav" aria-label="Explore the website"><a href="/properties/">All Bengaluru properties</a><a href="/films/">Property films</a><a href="/faqs/">Property FAQs</a><a href="/privacy/">Privacy notice</a><a href="/project-guide.pdf">SOBHA guide PDF</a></nav>`;
const businessDetails = [site.telephone?`<a href="tel:${e(site.telephone)}">${e(site.telephone)}</a>`:'',site.email?`<a href="mailto:${e(site.email)}">${e(site.email)}</a>`:'',site.address?`<span>${e(Object.values(site.address).join(', '))}</span>`:'',site.reraRegistration?`<span>RERA registration: ${e(site.reraRegistration)}</span>`:''].filter(Boolean).join(' · ');
const logo = `<a class="brand" href="/" aria-label="Trusted Properties home"><img class="brand-logo" src="/media/logo.svg" alt="Trusted Properties" width="105" height="105"/></a>`;
const header = `<header class="header">${logo}<nav id="navigation" aria-label="Main navigation"><a href="/properties/">Our properties</a><a href="/#developers">Our developers</a><a href="/films/">Property films</a><a href="/faqs/">Your questions</a></nav><a class="button small header-cta" href="/#enquire">Let’s find your home <span>↗</span></a><button class="menu-button" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation">☰</button></header>`;
const footer = `${discovery}<footer><div class="footer-top">${logo}<p>Good homes. New beginnings.</p><a class="text-link" href="/#enquire">Find your next home ↗</a></div>${businessDetails?`<p class="business-details">${businessDetails}</p>`:''}<div class="footer-bottom"><span>© 2026 Trusted Properties.</span><p>Trusted Properties is an independent multi-developer platform, not an official developer website. ${e(referenceNote)}</p><a href="/privacy/">Privacy notice</a></div></footer>`;
function breadcrumbs(items) {return `<nav class="breadcrumbs" aria-label="Breadcrumb"><ol>${items.map(([name,path],i)=>`<li>${i===items.length-1?`<span aria-current="page">${e(name)}</span>`:`<a href="${path}">${e(name)}</a>`}</li>`).join('')}</ol></nav>`;}
function documentPage(meta, content) {return `<!doctype html><html lang="en-IN"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><meta name="color-scheme" content="light"/><meta name="theme-color" content="#ffffff"/>${head(meta)}<link rel="icon" type="image/svg+xml" href="/favicon.svg"/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700&display=swap" rel="stylesheet"/><link rel="stylesheet" href="/src/style.css"/></head><body><a class="skip-link" href="#main">Skip to content</a>${header}<main id="main">${content}${enquirySection}</main>${footer}<script type="module" src="/src/pages.js"></script></body></html>`;}
async function save(path, text){await mkdir(dirname(path),{recursive:true});await writeFile(path,text);}
async function page(path,title,description,content,graph=[],extras={}) {const file=path==='/'?'index.html':`${path.slice(1)}index.html`;await save(file,documentPage({path,title,description,graph,...extras},content));pages.push({path,title,description,file});}
const faqHTML = entries => entries.map((faq,i)=>`<details class="faq-item"${i===0?' open':''}><summary>${e(faq.question)}</summary><p>${e(faq.answer)}</p></details>`).join('');
const galleryHTML = captions.map((caption,i)=>`<a class="gallery-item" href="${asset('photo',i+1,'webp')}" data-image="${i+1}" aria-label="View image: ${e(caption)}"><img src="${asset('photo',i+1,'webp')}" alt="${e(caption)} — illustrative residential reference image" loading="lazy" decoding="async"/><span>${e(caption)} <b>↗</b></span></a>`).join('');
const filmCards = (quick=false) => films.map((film,i)=>`<a class="film-card" href="${filmPath(i+1)}"${quick?` data-film="${i+1}"`:''} aria-label="Watch ${e(film[0])}"><div class="film-thumb"><img src="${asset('film',i+1,'jpg')}" alt="${e(filmDescriptions[i])}" loading="lazy" decoding="async"/><span class="film-play">▶</span></div><p>${String(i+1).padStart(2,'0')} &nbsp;${e(film[0])}<small>${film[1]}</small></p></a>`).join('');

const homeTemplate=await readFile('templates/home.html','utf8');
const enquiryOptions=enquiryDevelopers.map(name=>`<option value="${e(name)}">${e(name)}</option>`).join('');
const enquirySection=homeTemplate.match(/<section class="enquiry-section" id="enquire">[\s\S]*?<\/section>/)?.[0]?.replace('<!-- DEVELOPER_OPTIONS -->',enquiryOptions);
if(!enquirySection) throw new Error('Could not find the shared enquiry section in templates/home.html');
let home=homeTemplate;
const imageEntities=captions.map((caption,i)=>({'@type':'ImageObject','@id':url('/#reference-image-'+String(i+1).padStart(2,'0')),name:caption,caption:caption+' — artist’s impression from the supplied reference collection',contentUrl:url(asset('photo',i+1,'webp')),url:url(asset('photo',i+1,'webp'))}));
const homePage=webpage('/',homeTitle,site.description,'CollectionPage',{mainEntity:{'@id':url('/#collection')},about:{'@id':url('/#property-enquiry')},image:imageEntities.map(image=>({'@id':image['@id']}))});
home=home.replace('<!-- SEO_HEAD -->',head({path:'/',title:homeTitle,description:site.description,graph:[homePage,itemList(projects,'/'),service,...imageEntities],markdown:true})).replace('<!-- PROJECT_CARDS -->',projects.map(p=>renderProjectCard(p)).join('')).replace('<!-- GALLERY_ITEMS -->',galleryHTML).replace('<!-- FILM_ITEMS -->',filmCards(true)).replace('<!-- HOME_FAQS -->',`<section class="section home-faqs" id="faqs"><div class="section-heading"><div><div class="eyebrow">A CLEARER PICTURE</div><h2>Your questions.<br><em>Thoughtful answers.</em></h2></div><a href="/faqs/" class="text-link">Read all property FAQs ↗</a></div>${faqHTML(faqs.slice(0,4))}</section>`).replace('<!-- DISCOVERY_NAV -->',discovery+(businessDetails?`<p class="business-details">${businessDetails}</p>`:''));
const developerDescriptions = {
 'SOBHA':'Apartments and plotted communities, with homes across East, North and South Bengaluru.',
 'Puravankara':'Explore Purva BluBelle, Meraki and Atmosphere, from city addresses to spacious residences.',
 'Provident':'Discover Botanico, Ecopolitan, Sunworth City and the garden and terrace homes at Deansgate.',
 'DNR Group':'Discover DNR Arista: connected living on Bellandur’s Marathahalli–Sarjapur Outer Ring Road.'
};
const developerImages = {'SOBHA':'/media/photo-01.webp','Puravankara':'/media/projects/purva-blubelle.webp','Provident':'/media/projects/provident-botanico.webp','DNR Group':'/media/projects/dnr-arista.jpg'};
const heroSlides = developers.map((name,index)=>`<a class="hero-slide${index===0?' active':''}" data-hero-slide="${index}" href="/properties/?developer=${encodeURIComponent(name)}" aria-label="Explore ${e(name)} properties"${index===0?'':' hidden'}><img src="${developerImages[name] || '/media/photo-01.webp'}" alt="${e(name)} property collection" fetchpriority="${index===0?'high':'auto'}"/><span>${e(name)}</span></a>`).join('');
const featuredDevelopers = [
  {name:'SOBHA', logo:'/media/developer-logos/sobha.png', rank:'1st', href:'/properties/?developer=SOBHA'},
  {name:'Puravankara', logo:'/media/developer-logos/puravankara.png', rank:'2nd', href:'/properties/?developer=Puravankara'},
  {name:'Provident', logo:'/media/developer-logos/provident.png', rank:'3rd', href:'/properties/?developer=Provident'},
  {name:'DNR Group', logo:'/media/developer-logos/dnr.png', rank:'4th', href:'/properties/?developer=DNR%20Group'},
];
const comingSoonDevelopers = [
  {name:'Prestige Group', logo:'/media/developer-logos/prestige.png', rank:'6th'},
  {name:'Brigade Group', logo:'/media/developer-logos/brigade.png', rank:'7th'},
];
const developerTile = ({name,logo,rank,href}) => `<a class="developer-rank-card" href="${href}" aria-label="${e(name)}, ${e(rank)} developer collection"><span class="developer-rank-logo"><img src="${logo}" alt="${e(name)} logo" loading="lazy"/></span><span class="developer-rank-badge">${rank}</span></a>`;
const developerSection = `<h2 class="umbrella-title">Under the Trusted Properties Umbrella</h2><div class="umbrella-heading"><svg class="umbrella-mark" viewBox="0 0 600 180" role="img" aria-label="Trusted Properties Umbrella"><path d="M25 152 Q300 -96 575 152 Q515 106 455 152 Q375 92 300 152 Q220 98 145 152 Q85 112 25 152Z"/><path d="M300 122 V165 Q300 182 285 174"/><text x="300" y="88" text-anchor="middle">TRUSTED</text><text class="umbrella-subtitle" x="300" y="109" text-anchor="middle">PROPERTIES</text></svg></div><div class="developer-rank-grid">${featuredDevelopers.map(developerTile).join('')}</div><div class="coming-soon-divider"><span>COMING SOON</span></div><div class="developer-rank-grid developer-coming-grid">${comingSoonDevelopers.map(developerTile).join('')}<div class="developer-rank-card future-card"><span class="future-mark">?</span><span class="developer-rank-badge">8th</span></div><div class="developer-rank-card future-card"><span class="future-mark">?</span><span class="developer-rank-badge">9th</span></div></div>`;
home=home.replace('<!-- HERO_SLIDES -->',heroSlides).replace('<!-- DEVELOPER_OPTIONS -->',enquiryOptions).replaceAll('<!-- PROJECT_TOTAL -->',String(projects.length)).replaceAll('<!-- DEVELOPER_TOTAL -->',String(developers.length)).replace('<!-- DEVELOPERS -->',developerSection).replace('<!-- FILTERS -->',renderFilters(projects));
home=home.replace('<html lang="en">','<html lang="en-IN">');
await save('index.html',home);pages.push({path:'/',title:homeTitle,description:site.description,file:'index.html'});

const collectionPath='/properties/';
const collectionTitle='Bengaluru Properties: Compare Developers & Homes | Trusted Properties';
const collectionDescription=`Compare ${projects.length} properties from ${developers.join(', ')}. Explore locations, configurations, guide prices, amenities and completion information.`;
const collectionCrumbs=[['Home','/'],['Bengaluru properties',collectionPath]];
await page(collectionPath,collectionTitle,collectionDescription,`<section class="section detail-page">${breadcrumbs(collectionCrumbs)}<div class="eyebrow">THE BENGALURU COLLECTION</div><h1 id="collection-title">Different developers.<br><em>Your kind of home.</em></h1><p class="page-lead" id="collection-description">${e(collectionDescription)}</p><p class="source-note">${e(referenceNote)} Each project links to its own source.</p>${renderFilters(projects,true)}<p class="project-count" id="project-count" aria-live="polite">${projects.length} properties</p><div class="project-grid" id="project-grid">${projects.map(p=>renderProjectCard(p)).join('')}</div><div class="page-links"><a href="/faqs/">Questions about pricing and configurations?</a><a href="/#enquire">Request current details ↗</a></div></section>`,[webpage(collectionPath,collectionTitle,collectionDescription,'CollectionPage',{mainEntity:{'@id':url(collectionPath+'#collection')},breadcrumb:{'@id':url(collectionPath+'#breadcrumbs')}}),itemList(projects,collectionPath),breadcrumb(collectionPath,collectionCrumbs)],{markdown:true});

for(const p of projects){
 const reference = {'@type':'CreativeWork',name:p.sourceLabel,url:url(p.sourceUrl)};
 const path=projectPath(p), title=`${p.name}: ${p.config}, Price & Location | Trusted Properties`;
 const description=`Explore ${p.name} at ${p.location}. ${p.config}, ${p.size}. Guide price ${p.price}; request current pricing and availability.`;
 const crumbs=[['Home','/'],['Bengaluru properties',collectionPath],[p.name,path]];
 const projectEntity={'@type':p.type==='apartment'?'ApartmentComplex':'Place','@id':url(path+'#property'),name:p.name,url:url(path),description:`${p.config}; ${p.size}; ${p.area}; ${p.units}. ${p.details}`,address:{'@type':'PostalAddress',addressLocality:'Bengaluru',addressRegion:'Karnataka',addressCountry:'IN'},additionalProperty:[{'@type':'PropertyValue',name:'Location in project guide',value:p.location},{'@type':'PropertyValue',name:'Configuration',value:p.config},{'@type':'PropertyValue',name:'Size range in project guide',value:p.size},{'@type':'PropertyValue',name:'Guide completion',value:p.completion}]};
 const related=projects.filter(other=>other.id!==p.id&&(other.type===p.type||other.region===p.region)).slice(0,3);
 const content=`<section class="section detail-page" data-property-developer="${e(p.developer)}">${breadcrumbs(crumbs)}<div class="eyebrow">${e(p.developer)} / ${e(p.region.toUpperCase())} BENGALURU · ${e(p.type.toUpperCase())}</div><h1>${e(p.name)}</h1><p class="page-lead">${e(p.config)} at ${e(p.location)}.</p><figure class="detail-project-image"><img src="${e(p.image || '/media/photo-01.webp')}" alt="${e(p.image ? p.name+' developer reference' : 'Illustrative residential reference')}"/><figcaption>${e(p.imageNote || 'Illustrative reference · not project-specific')}</figcaption></figure><div class="project-detail-layout"><article><h2>Project at a glance</h2><dl class="property-facts">${[['Developer',p.developer],['Location',p.location],['Configurations',p.config],['Size range',p.size],['Community area',p.area],['Number of homes or plots',p.units],['Guide completion',p.completion],['RERA in source',p.rera]].map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${e(v)}</dd></div>`).join('')}</dl>${p.highlights.length?`<h2>What makes it stand out</h2><ul class="amenity-list">${p.highlights.map(h=>`<li>${e(h)}</li>`).join('')}</ul>`:''}<h2>Prices and configurations</h2><p>${e(p.details)}</p><h2>Location and project timeline</h2><p>${e(p.name)} is listed at ${e(p.location)}. The source lists its completion or possession status as: ${e(p.completion)}. Timelines and available configurations should be confirmed for the specific phase or unit you are considering.</p><h2>Before choosing your ${p.type==='plot'?'plot':'home'}</h2><p>Request the latest itemised cost sheet, current availability and applicable plans. Compare the listed size with the area definitions in the developer’s documents. Check the relevant approvals and RERA registration details directly with the developer.</p><p class="source-note">${e(referenceNote)} <a href="${e(p.sourceUrl)}">${e(p.sourceLabel)} ↗</a></p></article><aside class="project-enquiry-card"><div class="eyebrow">INDICATIVE GUIDE PRICE</div><strong>${e(p.price)}</strong><p>${e(p.priceNote)}. Current pricing and availability must be confirmed.</p><a class="button" href="/?project=${p.slug}#enquire">Request project details <span>↗</span></a><a href="/faqs/">Have a question? Read our FAQs.</a></aside></div><section class="related-projects"><div class="eyebrow">CONTINUE EXPLORING</div><h2>Other places to call home.</h2><div class="project-grid">${related.map(p=>renderProjectCard(p)).join('')}</div></section></section>`;
 await page(path,title,description,content,[webpage(path,title,description,'RealEstateListing',{mainEntity:{'@id':projectEntity['@id']},breadcrumb:{'@id':url(path+'#breadcrumbs')},citation:reference}),projectEntity,breadcrumb(path,crumbs)],{markdown:true});
 await save(`public${path}index.md`,`# ${p.name}\n\nCanonical page: ${url(path)}\n\n- Developer: ${p.developer}\n- RERA in source: ${p.rera}\n- Highlights: ${p.highlights.join('; ')}\n- Location: ${p.location}\n- Configuration: ${p.config}\n- Size range: ${p.size}\n- Community area: ${p.area}\n- Homes or plots: ${p.units}\n- Guide completion: ${p.completion}\n- Guide price: ${p.price} (${p.priceNote})\n\n## Prices and configurations\n\n${p.details}\n\n${referenceNote}\n\nSource: ${p.sourceLabel} — ${url(p.sourceUrl)}\n\nEnquire: ${url('/?project='+p.slug+'#enquire')}\n`);
}

const faqPath='/faqs/',faqTitle='Bengaluru Property FAQs | Trusted Properties',faqDescription='Answers about multi-developer project prices, configurations, residential plots, completion timelines, illustrative media and property enquiries in Bengaluru.';
const faqCrumbs=[['Home','/'],['Property FAQs',faqPath]];
await page(faqPath,faqTitle,faqDescription,`<section class="section reading-page">${breadcrumbs(faqCrumbs)}<div class="eyebrow">HELP WITH YOUR NEXT STEP</div><h1>Property questions.<br><em>Clear answers.</em></h1><p class="page-lead">A guide to the information in our Bengaluru property collection.</p>${faqHTML(faqs)}<div class="page-links"><a href="/properties/">Explore all properties ↗</a><a href="/#enquire">Ask about a project ↗</a></div></section>`,[webpage(faqPath,faqTitle,faqDescription,'FAQPage',{mainEntity:faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}})),breadcrumb:{'@id':url(faqPath+'#breadcrumbs')}}),breadcrumb(faqPath,faqCrumbs)],{markdown:true});

const filmsTitle='Property Films & Residential Walkthroughs | Trusted Properties',filmsDescription='Watch all eight supplied property films, from architecture and arrival areas to landscaped outdoor spaces and complete residential presentations.';
const filmCrumbs=[['Home','/'],['Property films','/films/']];
await page('/films/',filmsTitle,filmsDescription,`<section class="section detail-page">${breadcrumbs(filmCrumbs)}<div class="eyebrow">EXPLORE THE REFERENCE COLLECTION</div><h1>A closer look.<br><em>A new perspective.</em></h1><p class="page-lead">${filmsDescription}</p><p class="source-note">Visuals are artist’s impressions and reference presentations. They do not identify a specific available home; features vary by project.</p><div class="film-grid">${filmCards()}</div><div class="page-links"><a href="/properties/">Compare Bengaluru properties ↗</a></div></section>`,[webpage('/films/',filmsTitle,filmsDescription,'CollectionPage',{breadcrumb:{'@id':url('/films/#breadcrumbs')},mainEntity:{'@type':'ItemList',numberOfItems:8,itemListElement:films.map((f,i)=>({'@type':'ListItem',position:i+1,name:f[0],url:url(filmPath(i+1))}))}}),breadcrumb('/films/',filmCrumbs)]);

const videoEntities=[];
for(const [i,film] of films.entries()){
 const id=i+1,path=filmPath(id),title=`${film[0]} — Property Film | Trusted Properties`,description=filmDescriptions[i],crumbs=[...filmCrumbs,[film[0],path]];
 const [minutes,seconds]=film[1].split(':').map(Number);
 const video={'@type':'VideoObject','@id':url(path+'#video'),name:film[0],description,thumbnailUrl:[url(asset('film',id,'jpg'))],contentUrl:url(asset('film',id,'mp4')),url:url(path),duration:`PT${minutes}M${seconds}S`,isFamilyFriendly:true,...(site.videoUploadDates[id]?{uploadDate:site.videoUploadDates[id]}:{})};
 videoEntities.push(video);
 await page(path,title,description,`<section class="section watch-page">${breadcrumbs(crumbs)}<div class="eyebrow">REFERENCE FILM ${String(id).padStart(2,'0')} / 08 · ${film[1]}</div><h1>${e(film[0])}</h1><video class="watch-video" controls playsinline preload="metadata" poster="${asset('film',id,'jpg')}" aria-label="${e(film[0])}"><source src="${asset('film',id,'mp4')}" type="video/mp4"/><a href="${asset('film',id,'mp4')}">Open the video file</a></video><p class="page-lead">${e(description)}</p><p class="source-note">Supplied reference presentation; artist’s impressions may be shown. The footage is illustrative and is not a representation of confirmed inventory or the specifications of a particular available unit. Compare the project guide and ask for the applicable plans.</p><div class="page-links"><a href="/films/">All property films</a><a href="/properties/">Explore properties</a><a href="/#enquire">Request details ↗</a></div></section>`,[webpage(path,title,description,'WebPage',{mainEntity:{'@id':video['@id']},breadcrumb:{'@id':url(path+'#breadcrumbs')}}),video,breadcrumb(path,crumbs)],{image:asset('film',id,'jpg')});
}

const privacyTitle='Privacy Notice | Trusted Properties', privacyDescription='How Trusted Properties uses contact details and preferences submitted through its property enquiry form.';
await page('/privacy/',privacyTitle,privacyDescription,`<section class="section reading-page">${breadcrumbs([['Home','/'],['Privacy notice','/privacy/']])}<div class="eyebrow">YOUR INFORMATION</div><h1>Privacy notice</h1><h2>Information you provide</h2><p>The enquiry form requests your name, country code, mobile number, preferred developer, configuration, budget and consent. Email is optional. Please share only the information requested.</p><h2>How your enquiry is used</h2><p>When you submit the form, your details are sent to the Trusted Properties enquiry service hosted on Cloudflare Workers to respond to your property enquiry. By checking the consent box, you authorise Trusted Properties to contact you by call, SMS, WhatsApp or email about that enquiry.</p><h2>Your choices</h2><p>You can choose not to submit the form. You can ask the representative who contacts you to stop further communications or to delete your enquiry details.</p><h2>Website resources</h2><p>Property images and films are hosted with this website. Fonts are loaded from Google Fonts, so your browser contacts Google to retrieve them. This website does not use advertising or analytics cookies.</p><a class="text-link" href="/">Back to the website ↗</a></section>`,[webpage('/privacy/',privacyTitle,privacyDescription)]);

await save('404.html',documentPage({path:'/404.html',title:'Page Not Found | Trusted Properties',description:'Find your way back to the Trusted Properties collection.',noindex:true},'<section class="section reading-page"><div class="eyebrow">PAGE NOT FOUND</div><h1>Let’s find your way home.</h1><p class="page-lead">This address does not exist. Explore our Bengaluru property collection instead.</p><a class="button" href="/properties/">Explore properties ↗</a></section>'));

const xml = content => `<?xml version="1.0" encoding="UTF-8"?>\n${content}\n`;
await save('public/sitemap.xml',xml(`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['sitemap-pages.xml','sitemap-images.xml','sitemap-videos.xml'].map(file=>`<sitemap><loc>${url('/'+file)}</loc></sitemap>`).join('')}</sitemapindex>`));
await save('public/sitemap-pages.xml',xml(`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${url(p.path)}</loc></url>`).join('')}</urlset>`));
await save('public/sitemap-images.xml',xml(`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"><url><loc>${url('/')}</loc>${captions.map((_,i)=>`<image:image><image:loc>${url(asset('photo',i+1,'webp'))}</image:loc></image:image>`).join('')}</url></urlset>`));
await save('public/sitemap-videos.xml',xml(`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">${videoEntities.map((v,i)=>`<url><loc>${v.url}</loc><video:video><video:thumbnail_loc>${v.thumbnailUrl[0]}</video:thumbnail_loc><video:title>${e(v.name)}</video:title><video:description>${e(v.description)}</video:description><video:content_loc>${v.contentUrl}</video:content_loc><video:duration>${Number(films[i][1].split(':')[0])*60+Number(films[i][1].split(':')[1])}</video:duration>${v.uploadDate?`<video:publication_date>${v.uploadDate}</video:publication_date>`:''}</video:video></url>`).join('')}</urlset>`));
// A single group allows search and AI search crawlers without divergent policies.
await save('public/robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${url('/sitemap.xml')}\n`);
const markdownProjects=await Promise.all(projects.map(p=>readFile(`public${projectPath(p)}index.md`,'utf8')));
const markdownFAQs=faqs.map(f=>`## ${f.question}\n\n${f.answer}`).join('\n\n');
await save('public/llms.txt',`# Trusted Properties\n\n> Bengaluru property information and enquiry website covering ${projects.length} properties from SOBHA, Puravankara, Provident and DNR Group.\n\nTrusted Properties is an independent multi-developer platform, not an official developer website. All prices and completion dates are indicative information from the linked project sources, not live quotations or verified inventory. Visuals are illustrative.\n\n## Main pages\n\n- [Home](${url('/')}): Overview, imagery and enquiry form.\n- [All Bengaluru properties](${url('/properties/')}): Compare every listed project.\n- [Property FAQs](${url('/faqs/')}): Pricing, configurations, plots, timelines and enquiry information.\n- [Property films](${url('/films/')}): Eight supplied reference videos.\n\n## Project guides\n\n${projects.map(p=>`- [${p.name}](${url(projectPath(p))}): ${p.location}; ${p.config}; ${p.price} (${p.priceNote}).`).join('\n')}\n\n## Source and text versions\n\n- [Source project guide](${url('/project-guide.pdf')}): Supplied SOBHA reference; current details must be confirmed.\n- [Full text collection](${url('/llms-full.txt')}): Project facts and FAQ answers in one file.\n- [Project data](${url('/data/projects.json')}): Machine-readable facts and canonical links.\n- [Home in Markdown](${url('/index.md')}): Text version of the overview.\n- [Privacy notice](${url('/privacy/')}): Form data and contact consent.\n\nProject pages also have Markdown versions at their canonical directory URL followed by index.md. These text versions describe the same facts available to visitors.\n`);
const overview=`# Trusted Properties — multi-developer homes and plots in Bengaluru\n\n${site.description}\n\nTrusted Properties is an independent multi-developer platform, not an official developer website. ${referenceNote}\n\n${projects.map(p=>`- [${p.name}](${url(projectPath(p))}): ${p.location}. ${p.config}; ${p.size}; ${p.price} (${p.priceNote}).`).join('\n')}\n\n[Property FAQs](${url('/faqs/')}) · [Films](${url('/films/')}) · [Enquire](${url('/#enquire')})\n`;
await save('public/index.md',overview);await save('public/properties/index.md',overview);await save('public/faqs/index.md',`# Property FAQs\n\n${markdownFAQs}\n`);
await save('public/llms-full.txt',`${overview}\n\n${markdownProjects.join('\n\n')}\n\n# Property FAQs\n\n${markdownFAQs}\n\n# Films\n\n${films.map((f,i)=>`## ${f[0]}\n\n${filmDescriptions[i]}\n\nWatch: ${url(filmPath(i+1))}`).join('\n\n')}\n`);
await save('public/data/projects.json',JSON.stringify({sources:[...new Set(projects.map(p=>url(p.sourceUrl)))],disclaimer:referenceNote,projects:projects.map(p=>({...p,url:url(projectPath(p))}))},null,2)+'\n');
await save('public/_headers',`/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n/media/*\n  Cache-Control: public, max-age=86400\n/*.md\n  Content-Type: text/markdown; charset=utf-8\n/llms*.txt\n  Content-Type: text/plain; charset=utf-8\n/sitemap*.xml\n  Content-Type: application/xml; charset=utf-8\n/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n`);
await save('public/_redirects',`https://www.trustedproperties.net/* https://trustedproperties.net/:splat 301\n/index.html / 301\n${pages.filter(p=>p.path!=='/').map(p=>`${p.path}index.html ${p.path} 301`).join('\n')}\n`);
console.log(`Generated ${pages.length} indexable HTML pages, 404, structured data, 3 sitemaps, robots.txt and LLM-readable content.`);
