export const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
export const projectPath = project => `/properties/${project.slug}/`;
export function renderProjectCard(project, quickView = false) {
  const p = Object.fromEntries(Object.entries(project).map(([key,value]) => [key,escapeHtml(value)]));
  const path = projectPath(project);
  return `<article class="project-card"><a class="project-image" href="${path}" tabindex="-1" aria-hidden="true"><img src="${p.image || '/media/photo-01.webp'}" alt="" loading="lazy" decoding="async"/><span>${p.imageNote || 'Illustrative reference · not project-specific'}</span></a><div class="project-card-body"><div class="project-top"><span class="project-category">${p.developer}</span><span class="property-kind">${p.type}</span></div><h3><a href="${path}">${p.name}</a></h3><p class="project-location">⌖ ${p.location}</p><div class="project-specs"><span>${p.config}</span><span>·</span><span>${p.size}</span></div><dl class="card-facts"><div><dt>Community</dt><dd>${p.area}</dd></div><div><dt>Completion / possession</dt><dd>${p.completion}</dd></div></dl>${project.highlights.length?`<p class="card-highlights">${project.highlights.slice(0,3).map(escapeHtml).join(' · ')}</p>`:''}<div class="project-bottom"><div class="project-price">${p.price}<small>${p.priceNote}</small></div>${quickView ? `<button class="project-open" data-project="${p.id}" aria-label="View ${p.name} details">↗</button>` : `<a class="project-open" href="${path}" aria-label="View ${p.name} details">↗</a>`}</div><div class="card-links"><a href="${path}">View project details ↗</a><a href="/?project=${p.slug}#enquire">Enquire</a></div></div></article>`;
}
export function renderFilters(projects, listPage = false) {
  const options = field => [...new Set(projects.map(p=>p[field]))].map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');
  return `<div class="catalog-controls" data-js-only hidden><label class="catalog-search">Search properties<input id="property-search" type="search" placeholder="Project, location or developer…" autocomplete="off"/></label><div class="catalog-filters"><label>Developer<select id="developer-filter"><option value="all">All developers</option>${options('developer')}</select></label><label>Neighbourhood<select id="location-filter"><option value="all">All Bengaluru</option>${options('region')}</select></label><label>Property type<select id="type-filter"><option value="all">All property types</option>${options('type')}</select></label><button class="reset-filters" id="reset-filters" type="button">Reset filters ↺</button></div>${listPage?'<div class="view-toggle" role="group" aria-label="Property view"><button data-view="grid" aria-pressed="true">Grid view</button><button data-view="list" aria-pressed="false">List view</button></div>':''}</div>`;
}
